### ISSUE TITLE
ng build fails - explorer.service is missing

### ISSUE THREAD

**Issue by efosao** [skycoin/skycoin-explorer#61]
**ng build fails**
I tried to run the new build on master, but ran into build errors during the angular compile step. Details are as follows:

./src/app/services/explorer/explorer.service is missing from repo, but reference in /src/app/app.module.ts.

```js
// ./src/app/app.module.ts
import { AddressDetailComponent } from './components/pages/address-detail/address-detail.component';
import { TransactionsValuePipe } from './pipes/transactions-value.pipe';
import { ExplorerService } from './services/explorer/explorer.service'; // MISSING FOLDER
import { QrCodeComponent } from './components/layout/qr-code/qr-code.component';
import { FormsModule } from '@angular/forms';
...
```
build error msg

```bash
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ./services/explorer/explorer.service relative to /Users/efosaoyegun/Projects/skycoin/skycoin-explorer/src/app/app.module.ts., resolving symbol AppModule in /Users/efosaoyegun/Projects/skycoin/skycoin-explorer/src/app/app.module.ts, resolving symbol AppModule in /Users/efosaoyegun/Projects/skycoin/skycoin-explorer/src/app/app.module.ts
    at syntaxError (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at NgModuleResolver.resolve (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:14750:70)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:15402:60)
    at addNgModule (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:24268:58)
    at /Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:24279:14
    at Array.forEach (<anonymous>)
    at _createNgModules (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:24278:26)
    at analyzeNgModules (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:24153:14)
    at analyzeAndValidateNgModules (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:24163:35)
    at AotCompiler.analyzeModulesAsync (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler/bundles/compiler.umd.js:23797:46)
    at CodeGenerator.codegen (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (/Users/efosaoyegun/Projects/skycoin/skycoin-explorer/node_modules/@ngtools/webpack/src/plugin.js:386:44)
```

**Comment by gz-c** [comment]
@montycrypto is this a documentation problem?

**Comment by efosao** [comment]
@gz-c @montycrypto 
The broken angular build was missed because, (1) it isn't currently being tested in CI (it's only testing .go files), and (2) the repo contains with `pre-built` javascript files in the dist folder that will let you start the project giving you the false impression that the project is healthy. However as soon as you try to generate those angular/js build files yourself by running `npm run build` or `make build-ng`, you will get the build error msg above.

I can integrate testing for the javascript build into the CI as soon as the missing file(s) are added to `master` and the `make build-ng` starts working again.

**Comment by montycrypto** [comment]
Thanks! I see that we added "explorer" to .gitignore to exclude the generated go binary. This also ignored the explorer directory within the services directory. On my computer everything built just fine, because I do have the missing file.

Also, it might be good to note that we keep build files due to some issues with npm on servers hosted in China. Not really standard, but with good reason.

Will fix this ASAP.
